Controllers/NotlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciBilgiSistemi.Models.EntityFramework;
using OgrenciBilgiSistemi.Models;
namespace OgrenciBilgiSistemi.Controllers



{
    public class NotlarController : Controller
    {
        // GET: Notlar
        ObsSistemDBEntities db = new ObsSistemDBEntities();
        public ActionResult Index()
        {
            var SinavNotlar = db.TBLNOTLAR.ToList();
            return View(SinavNotlar);
        }
        [HttpGet]
        public ActionResult YeniSinav()
        {

            return View();
        }
        [HttpPost]
        public ActionResult YeniSinav(TBLNOTLAR tbn)
        {
            db.TBLNOTLAR.Add(tbn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult NotGetir(int id)
        {
            var GetirilecekNot = db.TBLNOTLAR.Find(id);
            return View("NotGetir", GetirilecekNot);
        }
        [HttpPost]
        public ActionResult NotGetir(TBLNOTLAR p8,int Sınav1,int Sınav2,int Sınav3, int Proje,Class1 model )
        {
            if(model.islem=="Hesapla")
            {
                int Ortalama = (Sınav1 + Sınav2 + Sınav3 + Proje) / 4;
                ViewBag.ort = Ortalama;

            }
            if (model.islem == "NotGuncelle")
            {

            }
            return View();
        }
        
    }
}

Views/Notlar/Index.cshtml
@using OgrenciBilgiSistemi.Models.EntityFramework
@model List<TBLNOTLAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered"
    <tr>
        <th>
            NOT ID
        </th>
        <th>
            ÖĞRENCİ
        </th>
        <th>
            DERS
        </th>
        <th>
            SINAV1
        </th>
        <th>
            SINAV2
        </th>
        <th>
            SINAV3
        </th>
        <th>
            PROJE
        </th>
        <th>
            ORTALAMA
        </th>
        <th>
            DURUM
        </th>
        <th>
            İŞLEMLER
        </th>
    </tr>
    <tbody>
@foreach (var sınav in Model)
{
        <tr>
            <td>
                @sınav.NotID
            </td>
            <td>
                @sınav.OgrenciID
            </td>
            <td>
                @sınav.DersID
            </td>
            <td>
                @sınav.Sınav1
            </td>
            <td>
                @sınav.Sınav2
            </td>
            <td>
                @sınav.Sınav3
            </td>
            <td>
                @sınav.Proje
            </td>
            <td>
                @sınav.Ortalama
            </td>
            <td>
                @sınav.Durum
            </td>
            <td>
                <a href="/Notlar/Sil/@sınav.OgrenciID" class="btn btn-danger">Sil</a>

                <a href="/Notlar/Notgetir/@sınav.OgrenciID" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
}
    </tbody>

</table>
<a href="/Notlar/YeniSinav" class="btn btn-primary">Yeni Sınav Girişi</a>

Views/Notlar/NotGetir.cshtml
@model OgrenciBilgiSistemi.Models.EntityFramework.TBLNOTLAR

@{
    ViewBag.Title = "NotGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Notlar", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.OgrenciID)
        @Html.TextBoxFor(m => m.OgrenciID, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Sınav1)
        @Html.TextBoxFor(m => m.Sınav1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Sınav2)
        @Html.TextBoxFor(m => m.Sınav2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Sınav3)
        @Html.TextBoxFor(m => m.Sınav3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Proje)
        @Html.TextBoxFor(m => m.Proje, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Ortalama)
        @Html.TextBoxFor(m => m.Ortalama, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Durum)
        @Html.TextBoxFor(m => m.Durum, new { @class = "form-control" })
    </div>

    @Html.HiddenFor(m => m.NotID)
    <div style="margin-top:15px">
        <button class="btn btn-group">Hesapla</button>

    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Güncelle</button>

    </div>

}

Views/Notlar/YeniSinav.cshtml
@{
    ViewBag.Title = "YeniSinav";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="post" class="form-group">
    <div>
        <label>Öğrenci ID</label>
        <input type="text" class="form-control" name="OgrenciID" />
    </div>
    <div style="margin-top:10px">
        <label>Ders Adı</label>
        <input type="text" class="form-control" name="DersID" />
    </div>
    <div style="margin-top:10px">
        <label>Sınav1</label>
        <input type="text" class="form-control" name="Sınav1" />
    </div>
    <div style="margin-top:10px">
        <label>Sınav2</label>
        <input type="text" class="form-control" name="Sınav2" />
    </div>
    <div style="margin-top:10px">
        <label>Sınav3</label>
        <input type="text" class="form-control" name="Sınav3" />
    </div>
    <div style="margin-top:10px">
        <label>Proje</label>
        <input type="text" class="form-control" name="Proje" />
    </div>
    <div style="margin-top:10px">
        <label>Ortalama</label>
        <input type="text" class="form-control" name="Ortalama" />
    </div>
    <div style="margin-top:10px">
        <label>Durum</label>
        <input type="text" class="form-control" name="Durum" />
    </div>

    <div style="margin-top:10px">
        <button class="btn btn-primary">Sınav Ekle</button>
    </div>
</form>